spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/common?currentSchema=common
    username: admin
    password: admin1!
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # create, create-drop, validate, none 중 선택
    show-sql: true
    properties:
      hibernate:
        format_sql: true