spring:
  # JTA Atomikos 설정
  jta:
    atomikos:
      datasource:
        # 주문 DB: MySQL 설정
        order-db:
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          unique-resource-name: orderDB_mysql
          xa-properties:
            user: admin
            password: admin1!
            url: jdbc:mysql://localhost:3306/common

        # 배송 DB: PostgreSQL 설정
        delivery-db:
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          unique-resource-name: deliveryDB_postgres
          xa-properties:
            user: admin
            password: admin1!
            url: jdbc:postgresql://localhost:5432/common

  # JPA 설정 (정확한 들여쓰기)
  jpa:
    # 1. Spring Boot가 직접 관리하는 핵심 설정 그룹
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    # 2. Hibernate에 그대로 전달되는 부가 설정 그룹
    properties:
      hibernate:
        format_sql: true